name: Build MoproFFI

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main
        types:
            - ready_for_review

    # Option to manually trigger the workflow
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout mopro-ffi
              uses: actions/checkout@v3

            - name: Set up Xcode environment
              run: |
                  sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
                  sudo xcodebuild -license accept

            # - name: unzip xcframework
            #   run: |
            #       unzip Sources/MoproiOSBindings/MoproBindings.xcframework.zip -d Sources/MoproiOSBindings

            - name: Run Package Build
              run: |
                  xcodebuild build \
                    -scheme MoproFFI \
                    -destination 'generic/platform=iOS'
